name: Lint

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Yarn install
        run: yarn
      - name: Add reporter
        run: echo "::add-matcher::.github/actions/lint/yarn-reporter.json"
      - name: Typescript & Lint check
        run: yarn lint
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Yarn install
        run: yarn
      - name: Run tests
        run: |
          yarn test --forceExit
